pipelines:
  - name: S_Matrix_0029
    configuration:
          nodePool: ""
    steps:
      - name: S_Matrix_0029
        type: Matrix
        stepMode: Bash
        stepletMultipliers:
          environmentVariables:
            - animal: dog
              bird: sparrow
            - animal: cat
              bird: crow
            - animal: cow
              bird: parrot
          runtimes:
            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 8.17.0  
            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 8.16.0 
          
        execution:
          onExecute:
            - echo "Executing matrix step on ${steplet_id}"
            - sleep 3m
            - echo "Variation animal = ${animal}, bird = ${bird}"
            - sleep 5m
